### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by sathia-musso** [danog/PrimeModule-ext#2]
# make
    mkdir -p shared/common
    mkdir -p shared/zend
    g++ -Wall -c -std=c++11 -fvisibility=hidden -DBUILDING_PHPCPP -Wno-write-strings -MD -g `php-config --includes` -fpic -o shared/zend/exception_handler.o zend/exception_handler.cpp
    /bin/sh: 1: php-config: not found
    In file included from zend/exception_handler.cpp:12:0:
    zend/includes.h:40:17: fatal error: php.h: No such file or directory
     #include <php.h>
                     ^
    compilation terminated.
    Makefile:204: recipe for target 'shared/zend/exception_handler.o' failed
    make: *** [shared/zend/exception_handler.o] Error 1

**Comment by YoilyL** [comment]
@sathio Install php-dev

**Comment by danog** [comment]
Exactly
