### ISSUE TITLE
PHP Warning: PHP Startup: Unable to load dynamic library undefined symbol: core_globals_id 

### ISSUE THREAD

**Issue by MrFiregore** [danog/PrimeModule-ext#3]
When execute all command to install ( `git clone https://github.com/CopernicaMarketingSoftware/PHP-CPP && cd PHP-CPP && make -j$(nproc) && sudo make install && cd .. && git clone https://github.com/danog/PrimeModule-ext && cd PrimeModule-ext && make -j$(nproc) && sudo make install` ) and run php -m, it display this error:
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/primemodule.so' - /usr/lib/libphpcpp.so.2.0: undefined symbol: core_globals_id in Unknown on line 0
`

My php version is:

```
PHP 7.0.28-1+0~20180306105118.16+jessie~1.gbpe20ff4 (cli) (built: Mar  6 2018 11:17:41) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-1+0~20180306105118.16+jessie~1.gbpe20ff4, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by danog** [comment]
Could I get the result of the installation command?

**Comment by MrFiregore** [comment]
[PHP-CPP.log](https://github.com/danog/PrimeModule-ext/files/1845544/PHP-CPP.log)
[PrimeModule-ext.log](https://github.com/danog/PrimeModule-ext/files/1845545/PrimeModule-ext.log)

**Comment by danog** [comment]
@firegore2 Delete all versions of php, and reinstall php using https://docs.madelineproto.xyz/docs/REQUIREMENTS.html
